include:
  project: "shopware/6/product/platform"
  ref: "trunk"
  file: ".gitlab/templates/plugin.yml"

variables:
  PLATFORM_MIN_VERSION: "v6.3.5.0"

validate snippets:
  rules:
    - when: never

validate zip:
  allow_failure: true
