variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: 'tcp://docker:2375'
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public
    DEVELOPMENT_BRANCH: 'master'
    PLATFORM_BRANCH: 'master'
    RUN_IN_MR: 'true'

stages:
    - Static validation
    - Testing

default:
    image: shopware/development:latest
    before_script:
        - zip -rq plugin.zip .
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git --branch $DEVELOPMENT_BRANCH
        - rm -rf development/platform
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform --branch $PLATFORM_BRANCH
        - unzip -q plugin.zip -d development/custom/plugins/SwagLanguagePack
        - cd development
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &

Check built JS files:
    only:
        refs:
            - merge_requests
            - master
    stage: Static validation
    services:
        -   name: mysql:5.7
            alias: mysql
    allow_failure: true
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagLanguagePack
        - ./psh.phar administration:install-dependencies
        - ./psh.phar administration:build
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagLanguagePack
        - >
            if ! git diff --quiet --ignore-submodules HEAD --; then
                echo "Built Javascript files differ. Update the dependencies and execute 'administration:build' and 'storefront:build' again";
                git status;
                exit 1;
            else
                echo "Everything ok"
                exit 0;
            fi

Static analyze:
    stage: Static validation
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagLanguagePack
        - make init
        - >
            if [ -f "../../../vendor/shopware/platform/easy-coding-standard.php" ];
            then
                php ../../../dev-ops/analyze/vendor/bin/ecs check --config=../../../vendor/shopware/platform/easy-coding-standard.php src tests
            else
                php ../../../dev-ops/analyze/vendor/bin/ecs check --config=../../../vendor/shopware/platform/easy-coding-standard.yml src tests
            fi;
        - make phpstan
        - make psalm
        - make administration-lint
    rules:
        -   if: '$CI_COMMIT_BRANCH == "master"'
        -   if: '$RUN_IN_MR == "true" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    parallel:
        matrix:
            -   PLATFORM_BRANCH: '6.3.0.0'
                DEVELOPMENT_BRANCH: '6.3.2.0'
            -   PLATFORM_BRANCH: '6.3.0.1'
                DEVELOPMENT_BRANCH: '6.3.2.0'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.0.2'
                DEVELOPMENT_BRANCH: '6.3.2.0'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.1.0'
                DEVELOPMENT_BRANCH: '6.3.2.0'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.1.1'
                DEVELOPMENT_BRANCH: '6.3.2.0'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.2.0'
                DEVELOPMENT_BRANCH: '6.3.2.0'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.3.0'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: 'master'
                DEVELOPMENT_BRANCH: 'master'

ToDos resolved:
    only:
        refs:
            - merge_requests
            - master
    stage: Static validation
    allow_failure: true
    script:
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagLanguagePack
        - if [[ -n $CI_COMMIT_BRANCH ]]; then bin/check-todos.sh $CI_COMMIT_BRANCH; else bin/check-todos.sh $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME; fi

PHPUnit Coverage (6.3.x.x dev):
    only:
        refs:
            - merge_requests
            - master
    stage: Testing
    services:
        -   name: mariadb:10.3
            alias: mysql
    script:
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagLanguagePack
        - make init
        - cd $CI_PROJECT_DIR/development
        - composer dump-autoload -d custom/plugins/SwagLanguagePack
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            vendor/bin/phpunit
            --configuration custom/plugins/SwagLanguagePack/phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-clover build/artifacts/phpunit.clover.xml
            --coverage-html build/artifacts/phpunit-coverage-html
            --coverage-text

    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - development/build/artifacts/phpunit.clover.xml
        reports:
            junit: development/build/artifacts/phpunit.junit.xml

PHPUnit:
    stage: Testing
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagLanguagePack
        - make init
        - make phpunit
    rules:
        -   if: '$CI_COMMIT_BRANCH == "master"'
        -   if: '$RUN_IN_MR == "true" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    parallel:
        matrix:
            -   PLATFORM_BRANCH: '6.3.0.0'
                DEVELOPMENT_BRANCH: 'master'
            -   PLATFORM_BRANCH: '6.3.0.1'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.0.2'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.1.0'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.1.1'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.2.0'
                DEVELOPMENT_BRANCH: '6.3.2.0'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: '6.3.3.0'
                DEVELOPMENT_BRANCH: 'master'
                RUN_IN_MR: 'false'
            -   PLATFORM_BRANCH: 'master'
                DEVELOPMENT_BRANCH: 'master'
