include:
  project: "shopware/6/product/platform"
  ref: "trunk"
  file: ".gitlab/templates/plugin.yml"

variables:
  GIT_USER: shopwareBot
  GIT_EMAIL: shopwareBot@shopware.com
  PLATFORM_BRANCH: "trunk"
  BRANCH: "master"
  LANGUAGES: "bg-BG bs-BA cs-CZ da-DK el-GR en-US es-ES fi-FI fr-FR hi-IN hr-HR hu-HU id-ID it-IT ko-KR lv-LV nn-NO nl-NL pl-PL pt-PT ro-RO ru-RU sk-SK sl-SI sr-RS sv-SE tr-TR uk-UA vi-VN"

validate snippets:
  rules:
    - when: never

download translations:
    allow_failure: true
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        when: manual
    script:
        - git config --global user.name $GIT_USER
        - git config --global user.email $GIT_EMAIL
        - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.shopware.com/shopware/6/services/swaglanguagepack.git
        - git fetch gitlab_origin
        - git switch -c $BRANCH gitlab_origin/$BRANCH
        - ./bin/download-translations.sh $LANGUAGES
        - git add ./src
        - git commit -m "Update translations $CI_PIPELINE_CREATED_AT"
        - git push gitlab_origin $BRANCH
