include:
  project: "shopware/6/product/platform"
  ref: "6.4"
  file: ".gitlab/templates/plugin.yml"

variables:
  PLATFORM_MIN_VERSION: "v6.4.8.2"
  PLATFORM_BRANCH: "6.4"

validate snippets:
  rules:
    - when: never

validate zip:
  allow_failure: true
