name: Administration
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  unit:
    uses: shopware/github-actions/.github/workflows/admin-jest.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
      shopwareVersion: trunk
      uploadCoverage: true
    secrets:
      codecovToken: ${{ secrets.CODECOV_TOKEN }}
